### ISSUE TITLE
感谢与建议

### ISSUE THREAD

**Issue by tsosunchia** [Archeb/opentrace#1]
非常激动，NextTrace终于有了非常优秀完备的图形化二创🎆，作为Nexttrace开发团队的一员非常感谢此项目的作者让我再次看到了开源社区的行动力🙏以及非常乐见越来越多的二创。
提一个小建议，Nexttrace[这个commit](https://github.com/sjlleo/nexttrace/commit/4890615a2b46221fa0a0cb4284e9a127045a1a9f)中的两个ENV不知道您注意到没有，还有这个ENV`# 纯真IP数据库默认使用 http://127.0.0.1:2060 作为查询接口，如需自定义请使用环境变量
export NEXTTRACE_CHUNZHENURL=http://127.0.0.1:2060`,如果您能把这几个环境变量加入到preference内我想会大有裨益的。
再次感谢开发者🫡。

**Comment by Archeb** [comment]
感谢提醒，现在正在画Preference的UI了，这就把它加进去。

同时我也在仔细研究其他NextTrace的参数，想办法让用户更便捷直观的设置常用和不常用的选项。

**Comment by tsosunchia** [comment]
等您正式发版后，我们打算将您的repo地址po到Nexttrace Readme处方便更多gui用户使用。

**Comment by tsosunchia** [comment]
如果(仅是建议)您有任何意见和反馈，欢迎您随时与我们联系。

**Comment by tsosunchia** [comment]
> 如果您有任何意见和反馈，欢迎您随时与我们联系。![image](https://github.com/Archeb/opentrace/assets/59512455/50389a15-c380-4c36-8055-721a196d1ba7)
> 如果您愿意的话，可以加我lark，这样我可以将您加入开发者群里。

当然如果您愿意以Email的方式与我们联系也是没有任何问题的。

**Comment by Archeb** [comment]
已经添加了
