### ISSUE TITLE
地图连线错误

### ISSUE THREAD

**Issue by People-11** [Archeb/opentrace#11]
如图
![image](https://github.com/Archeb/opentrace/assets/41558215/57d3fba8-3e4f-4edc-9afb-923dc6cf3ee4)

**Comment by People-11** [comment]
![2023-06-05 01-18-42](https://github.com/Archeb/opentrace/assets/41558215/62cce3f8-df0e-423a-a268-54260bb76110)

**Comment by Archeb** [comment]
这个问题不太好解决，暂时在 064eec17594ee87fe5eb97d42f1108d258867f77 中把大地线模式（geodesic）关闭了，不知道问题是否改善？

**Comment by People-11** [comment]
连线有所改善，但轨迹还是很奇怪，真正的给人绕地球一周的感觉
![image](https://github.com/Archeb/opentrace/assets/41558215/9712edcb-8eae-4dce-a655-92266b213e4d)

**Comment by People-11** [comment]
即使手动移动到太平洋视角也还是从印度洋和大西洋上走
![image](https://github.com/Archeb/opentrace/assets/41558215/6947fae8-c6b4-4cca-943e-45af70a9d88f)

**Comment by Archeb** [comment]
开大地线模式就是为了能让连线从太平洋走，但是开了又有bug，所以现在只能先这样了。回头我再用一些其他workaround解决吧。

**Comment by Archeb** [comment]
已添加谷歌地图支持，可以换用谷歌地图；百度地图的该问题暂时搁置。
