### ISSUE TITLE
macOS应用的图标太大了

### ISSUE THREAD

**Issue by NekoLSD** [Archeb/opentrace#12]
<img width="193" alt="截屏2023-06-05 上午5 06 07" src="https://github.com/Archeb/opentrace/assets/121491490/a4d9a8f3-68f3-46c7-9b3d-e850d460e913">

**Comment by Archeb** [comment]
![image](https://github.com/Archeb/opentrace/assets/11910831/e70009b0-6c57-47ab-ad30-84e9afa0c40d)
已在 ffb8f4d74dc8d21cd2a1687e0c546842357c2d5b 中修复，更新[已发版](https://github.com/Archeb/opentrace/releases/tag/v1.2.2.0)
