### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by mclovin-2k** [Archeb/opentrace#13]
![123](https://github.com/Archeb/opentrace/assets/5440567/922dbe53-f6ef-4107-a9b1-f8949d7071a2)

**Comment by Archeb** [comment]
Duplicate with #4.

**Comment by tsosunchia** [comment]
您可以查看[此处](https://github.com/sjlleo/nexttrace-core/issues/131#issuecomment-1579145769)，可能有助于解答您的问题
