### ISSUE TITLE
看不懂，乱码

### ISSUE THREAD

**Issue by szzys** [Archeb/opentrace#15]
2023/06/05 19:24:08 绾湡 璇锋眰瓒呮椂(2s)锛岃鍒囨崲鍏朵粬API浣跨敤
2023/06/05 19:24:10 绾湡 璇锋眰瓒呮椂(2s)锛岃鍒囨崲鍏朵粬API浣跨敤
2023/06/05 19:24:12 绾湡 璇锋眰瓒呮椂(2s)锛岃鍒囨崲鍏朵粬API浣跨敤
2023/06/05 19:24:14 绾湡 璇锋眰瓒呮椂(2s)锛岃鍒囨崲鍏朵粬API浣跨敤

**Comment by Archeb** [comment]
乱码翻译过来是： “纯真 请求超时(2s)，请切换其他API使用”

使用纯真数据库，需要在本地搭建API。建议您切换其他IP地理位置信息数据库使用。
