### ISSUE TITLE
bad handshake

### ISSUE THREAD

**Issue by im1989** [Archeb/opentrace#18]
2023/06/11 00:54:49 dial: websocket: bad handshake
2023/06/11 00:54:50 dial: websocket: bad handshake
2023/06/11 00:54:51 dial: websocket: bad handshake
2023/06/11 00:54:51 dial: websocket: bad handshake
2023/06/11 00:54:52 dial: websocket: bad handshake
2023/06/11 00:54:53 dial: websocket: bad handshake
2023/06/11 00:54:55 dial: websocket: bad handshake
2023/06/11 00:54:57 dial: websocket: bad handshake
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xf2fbd4]

goroutine 1 [running]:
github.com/gorilla/websocket.(*Conn).Close(0xc0000bbab8?)
	github.com/gorilla/websocket@v1.5.0/conn.go:345 +0x14
github.com/xgadget-lab/nexttrace/cmd.Excute.func1()
	github.com/xgadget-lab/nexttrace/cmd/cmd.go:165 +0x25
github.com/xgadget-lab/nexttrace/cmd.Excute()
	github.com/xgadget-lab/nexttrace/cmd/cmd.go:315 +0x1f73
main.main()
	github.com/xgadget-lab/nexttrace/main.go:8 +0x17

**Comment by Archeb** [comment]
请参考 #4
