### ISSUE TITLE
[BUG] 代理设置填入 http://127.0.0.1:7890 后无法打开

### ISSUE THREAD

**Issue by betaxab** [Archeb/opentrace#20]
**Describe the bug 描述你遇到的BUG**

代理设置填入 http://127.0.0.1:7890 后无法打开

**To Reproduce 复现方法**

设置-代理设置 填入 http://127.0.0.1:7890

**Screenshots (If applicable) 截图（如果有）**

**Environment 使用环境**
 - OS 操作系统：Windows 11 22H2 
 - Version 程序版本：22621.1928

**Additional context 补充说明**

**Comment by tsosunchia** [comment]
nexttrace-bin的版本是什么？
是否为v1.7.2-2-2

**Comment by betaxab** [comment]
C:\Users\beta>nexttrace -v
NextTrace v1.1.7-2 2023-06-06T19:36:21Z b1edef3

**Comment by tsosunchia** [comment]
你更新到v1.7.2-2-2 再尝试一下
https://github.com/nxtrace/Ntrace-V1/releases/tag/v1.1.7-2-2

**Comment by tsosunchia** [comment]
另外 “无法打开” 指的是？

**Comment by betaxab** [comment]
已经更换，一个样。

无法打开即：

双击 OpenTrace.exe （或右键点打开 或 以管理员运行）均无任何界面弹出，无任何报错，只是鼠标刷新环转了一下。

**Comment by tsosunchia** [comment]
您确定 [7890](http://127.0.0.1:7890/) 端口是http proxy吗？

**Comment by betaxab** [comment]
是的，clash 的 mixport，支持 http 和 socks5，allow lan 已经开启，防火墙已经放行，另外已经试过关闭 clash，同样无法再次打开 opentrace，除非将 opentrace 的文件夹名修改为别的

**Comment by tsosunchia** [comment]
> 是的，clash 的 mixport，支持 http 和 socks5，allow lan 已经开启，防火墙已经放行，另外已经试过关闭 clash，同样无法再次打开 opentrace，除非将 opentrace 的文件夹名修改为别的

我刚才也测试了一下，连接本地xray的socks 和 http端口，都可以正常用。

请您尝试了一下 直接运行nexttrace-bin 进行路由测试 看看是否有运行问题？

**Comment by tsosunchia** [comment]
另外你是指opentrace 的界面都无法看见了吗？

如果是这样，那跟您设置了代理应该没有关系。

**Comment by betaxab** [comment]
> 另外你是指opentrace 的界面都无法看见了吗？

是的。只要填入 http://127.0.0.1:7890 ，关闭应用后，就“无法看见了”

已经测试把 opentrace.exe 删掉，也是一样的结果。

> 请您尝试了一下 直接运行nexttrace-bin 进行路由测试 看看是否有运行问题？

由于电脑在国内，无法连上 api，所以无法直接路由测试。

**Comment by tsosunchia** [comment]
> 由于电脑在国内，无法连上 api，所以无法直接路由测试。

您同样设置代理，就可以访问了呀 (配置NEXTTRACE_PORXY环境变量)

> 是的。只要填入 http://127.0.0.1:7890/ ，关闭应用后，就“无法看见了”

大概是opentrace的问题，您尝试一下重新下载opentrace呢？

**Comment by betaxab** [comment]
> 大概是opentrace的问题，您尝试一下重新下载opentrace呢？

是啊，所以发 issue 看如何解决。我只要重命名一下文件夹，就可以打开了

**Comment by betaxab** [comment]
> 问题收到，我有空看看能不能复现。

我将 AppData\Local\IsolatedStorage\ 下文件夹删掉后，opentrace 就可以打开了

**Comment by Archeb** [comment]
> > 问题收到，我有空看看能不能复现。
> 
> 我将 AppData\Local\IsolatedStorage\ 下文件夹删掉后，opentrace 就可以打开了

好的，这个是存放配置的位置。删掉之后设置其他选项能够复现这个问题吗？

**Comment by betaxab** [comment]
> 好的，这个是存放配置的位置。删掉之后设置其他选项能够复现这个问题吗？

嗯，我刚刚测试，跟“代理设置”无关，因为我尝试修改 opentrace 设置里其他的任何一个选项，也是会导致应用无法打开。

**Comment by betaxab** [comment]
@Archeb 已经发现问题：

设置-Language（语言）默认为 空，如果将其设置为任何语言，则可解决这个问题。

**Comment by Archeb** [comment]
> @Archeb 已经发现问题：
> 
> 设置-Language（语言）默认为 空，如果将其设置为任何语言，则可解决这个问题。

感谢，我稍后会修复这个问题。
