### ISSUE TITLE
[BUG] Linux上缺失依赖 以及百度地图无法显示

### ISSUE THREAD

**Issue by Glucy-2** [Archeb/opentrace#22]
**Describe the bug 描述你遇到的BUG**
程序报错无法启动:
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libwebkit2gtk-4.0.so.37' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibwebkit2gtk-4.0.so.37: 无法打开共享对象文件: 没有那个文件或目录
   at Eto.GtkSharp.NativeMethods.NMLinux.webkit_web_view_new()
   at Eto.GtkSharp.NativeMethods.webkit_web_view_new()
   at Eto.GtkSharp.Forms.Controls.WebViewHandler..ctor()
   at Eto.GtkSharp.Platform.<>c.<AddTo>b__12_61()
   at Eto.Widget..ctor()
   at OpenTrace.MainForm..ctor() in /home/runner/work/opentrace/opentrace/MainForm.cs:line 132
   at OpenTrace.Program.Main(String[] args) in /home/runner/work/opentrace/opentrace/Program.cs:line 36
[1]    95980 IOT instruction (core dumped)  OpenTrace
```
安装 `libwebkit2gtk-4.0-37` 包后程序能够启动，但是点击开始按钮有概率弹出此错误信息:（另外建议加一个回车开始的功能）
![图片](https://github.com/Archeb/opentrace/assets/53287753/ad252ff6-0514-455c-97cf-6c86d3f98a5d)

百度地图无法显示:
![图片](https://github.com/Archeb/opentrace/assets/53287753/298293ea-0af2-4425-970a-5d0b98a8db21)

**Environment 使用环境**
 - OS: Debian GNU/Linux trixie/testing x86_64 
 - Kernel: 6.4.0-3-amd64 
 - DE: Plasma 5.27.7 (wayland)
 - Version 程序版本: 1.2.4.1

**Comment by Archeb** [comment]
![image](https://github.com/Archeb/opentrace/assets/11910831/361df9d8-047a-4e96-99a8-5e2134384453)

我这边测试  ArchLinux 6.1.45-1 KDE Plasma 上使用 webkit2gtk 2.40.5-2 包，浏览器是没啥问题的

回车开始这个其实是做了的，Windows 和 macOS 都能正常工作；Linux 为啥不行我再研究一下。

**Comment by Glucy-2** [comment]
我试了X11和Wayland,百度地图都不显示

**Comment by Archeb** [comment]
回车的问题已经在 4759b4dd782b649639040090267d425bbcd47512 修复

浏览器这里我也只是引入了一下webview，Eto.Form（上游GUI框架）提供的可配置项其实很少，也没有什么debug办法……看不到什么修复的办法

**Comment by fakeboboliu** [comment]
在我的 sid 中正常，Cinnamon@X11

![图片](https://github.com/Archeb/opentrace/assets/7552030/55a26509-41f0-4abb-b5f4-58f4cf1de7c0)

**Comment by Glucy-2** [comment]
那可能是我这边的问题了

**Comment by leohearts** [comment]
> 那可能是我这边的问题了

![image](https://github.com/Archeb/opentrace/assets/24632029/c8bbee9e-d6fc-493e-88eb-143df5405c5a)

我这也遇到了同样的问题

**Comment by leohearts** [comment]
![image](https://github.com/Archeb/opentrace/assets/24632029/7b2f24f7-5e02-4746-b312-9b0ddd9d7241)

WEBKIT_DISABLE_COMPOSITING_MODE=1 + Google maps = okay
WEBKIT_DISABLE_COMPOSITING_MODE=1 = Baidu maps = crash
no WEBKIT_DISABLE_COMPOSITING_MODE=1 = crash

**Comment by fakeboboliu** [comment]
> WEBKIT_DISABLE_COMPOSITING_MODE=1

你们有在使用英伟达显卡的笔记本吗？ 我注意到这里有一些与这个相关的问题讨论：
https://bugs.webkit.org/show_bug.cgi?id=180739

**Comment by leohearts** [comment]
> > WEBKIT_DISABLE_COMPOSITING_MODE=1
> 
> 你们有在使用英伟达显卡吗？ 我注意到这里有一些与这个相关的问题讨论：
> https://bugs.webkit.org/show_bug.cgi?id=180739

我用 amd

**Comment by leohearts** [comment]
changing to gnome.Sdk:44 and compile our own webkitgtk:4 fixed this ! If this can be listed on flathub just use the flatpak version. (or build your own and install from local source)
