### ISSUE TITLE
[Feature Request] Right click to copy address

### ISSUE THREAD

**Issue by hanyan-rst** [Archeb/opentrace#23]
**Is your feature request related to a problem? Please describe. 您所请求的功能是否和某个问题有关？如果有，请说明**
No

**Describe the solution you'd like 描述您想要的功能**
Hope can copy the ip address of a node in the path by right-click.

**Describe alternatives you've considered (If applicable) 可能备选方案（如果有）**

**Additional context 补充说明**

**Comment by Archeb** [comment]
In development
![image](https://github.com/Archeb/opentrace/assets/11910831/c50dd25d-9e2b-4dbc-b4c6-97c8c18adc0b)

**Comment by hanyan-rst** [comment]
Thanks. Looking forward to the release.

**Comment by Archeb** [comment]
feature added in 7c6a1cee274e7ccbe080d74a2cb7190f9db537d9
