### ISSUE TITLE
[Feature Request] 可以支持下GeoLite2 的mmdb本地库吗

### ISSUE THREAD

**Issue by ThreeSourLemon** [Archeb/opentrace#24]
**Is your feature request related to a problem? Please describe. 您所请求的功能是否和某个问题有关？如果有，请说明**

**Describe the solution you'd like 描述您想要的功能**
感觉geolite2的库挺准的

**Describe alternatives you've considered (If applicable) 可能备选方案（如果有）**

**Additional context 补充说明**

**Comment by tsosunchia** [comment]
和现有的其他离线库相比有什么优势吗？

**Comment by tsosunchia** [comment]
> > 和现有的其他离线库相比有什么优势吗？
> 
> ip2region一点都不准 刚注册ipinfo 下载用了下 这个还可以 感觉和geolite是一个库？
> 
> https://github.com/P3TERX/GeoLite.mmdb 这里有个geolite库配合自动下载应该更方便使用把

ipinfo离线库和geolite比起来呢？

此时geolite是否还有明显优势？

**Comment by ThreeSourLemon** [comment]
> > > 和现有的其他离线库相比有什么优势吗？
> > 
> > 
> > ip2region一点都不准 刚注册ipinfo 下载用了下 这个还可以 感觉和geolite是一个库？
> > https://github.com/P3TERX/GeoLite.mmdb 这里有个geolite库配合自动下载应该更方便使用把
> 
> ipinfo离线库和geolite比起来呢？
> 
> 此时geolite是否还有明显优势？
准确性的话感觉应该差不多 没对比很多 具体不是很清楚
但是看文件大小ipinfo 33m geolite 60m 可能会更好？

能不注册账户从github下载数据库的话 易用性更好吧

**Comment by tsosunchia** [comment]
> > > > 和现有的其他离线库相比有什么优势吗？
> > > 
> > > 
> > > ip2region一点都不准 刚注册ipinfo 下载用了下 这个还可以 感觉和geolite是一个库？
> > > https://github.com/P3TERX/GeoLite.mmdb 这里有个geolite库配合自动下载应该更方便使用把
> > 
> > 
> > ipinfo离线库和geolite比起来呢？
> > 此时geolite是否还有明显优势？
> > 准确性的话感觉应该差不多 没对比很多 具体不是很清楚
> > 但是看文件大小ipinfo 33m geolite 60m 可能会更好？
> 
> 能不注册账户从github下载数据库的话 易用性更好吧

从我的使用体验来说，geolite加了等于没加，准确度太低了

**Comment by Archeb** [comment]
我也想提供一些更丰富的GeoIP选择，不过这类问题目前应该是属于上游NextTrace的，请到NextTrace项目中提交issue。
