### ISSUE TITLE
[BUG] Unexpected string truncate in hostname

### ISSUE THREAD

**Issue by hanyan-rst** [Archeb/opentrace#25]
**Describe the bug 描述你遇到的BUG**
Unexpected hostname string truncate

**To Reproduce 复现方法**
When resolving iKuai default hostname 'iKuaiOS', the last letter 'S' was abandoned.

**Screenshots (If applicable) 截图（如果有）**
![image](https://github.com/Archeb/opentrace/assets/48790213/7dcd3b92-5253-45ef-9834-e5aad836536d)

**Environment 使用环境**
 - OS 操作系统：Windows 10 22H2
 - Version 程序版本：1.3.0.1

**Additional context 补充说明**

**Comment by Archeb** [comment]
Can't reproduce.
![image](https://github.com/Archeb/opentrace/assets/11910831/b46afee4-7fd1-43fb-9120-43bf60d5ea91)

**Comment by hanyan-rst** [comment]
Solved after add parameter "-a" in setting. Might be upstream project bug. Thanks!

**Comment by tsosunchia** [comment]
> Solved after add parameter "-a" in setting. Might be upstream project bug. Thanks!

你可以尝试一下 使用nexttrace --raw参数，来确认是否是上游问题
