### ISSUE TITLE
[Feature Request] Hard to find version in the program

### ISSUE THREAD

**Issue by hanyan-rst** [Archeb/opentrace#26]
**Is your feature request related to a problem? Please describe. 您所请求的功能是否和某个问题有关？如果有，请说明**

**Describe the solution you'd like 描述您想要的功能**
Hope there will be a version or about page including version info in the program.

**Describe alternatives you've considered (If applicable) 可能备选方案（如果有）**

**Additional context 补充说明**

**Comment by Archeb** [comment]
You can easily find the version in the properties window of the executable. 
![image](https://github.com/Archeb/opentrace/assets/11910831/e16457de-ac5e-4649-90ed-497cccd57e62)
