### ISSUE TITLE
[Feature Request] Enlarge the map window

### ISSUE THREAD

**Issue by People-11** [Archeb/opentrace#27]
**Is your feature request related to a problem? Please describe. 您所请求的功能是否和某个问题有关？如果有，请说明**

**Describe the solution you'd like 描述您想要的功能**
In the initial state, the map and the tracking list each take up half of the entire window, but I would like the map to be a bit larger, allocating the window as 35% tracking list and 65% map, which would give a better visual tracking experience

**Describe alternatives you've considered (If applicable) 可能备选方案（如果有）**

**Additional context 补充说明**
Like this
![image](https://github.com/Archeb/opentrace/assets/41558215/56510768-5d9c-4653-9dbe-183bd0f572ea)

**Comment by Archeb** [comment]
Probably we can make the ratio of row height a persistent setting? Will consider implementing this in the near future.

**Comment by Archeb** [comment]
feature added in a6df2f05fe868b18175663efd431d23a7422bb7d
