### ISSUE TITLE
[Feature Request] 添加单独的IP信息查询功能

### ISSUE THREAD

**Issue by Dragon-Lu** [Archeb/opentrace#29]
**Is your feature request related to a problem? Please describe. 您所请求的功能是否和某个问题有关？如果有，请说明**
无

**Describe the solution you'd like 描述您想要的功能**
可以只查询IP信息而不进行路由追踪，查询IP和路由追踪这两个功能经常会一起用到。可以做一个单独的页面或者按钮。如果能软件做在后台监视剪切板查询就更是锦上添花了。

**Describe alternatives you've considered (If applicable) 可能备选方案（如果有）**

**Additional context 补充说明**

**Comment by Archeb** [comment]
OpenTrace 是一个跨平台项目，而后台查询不管是小挂件、托盘图标还是剪贴板监听的功能，根据平台的不同，在实现上都会有很大差异，更适合单独为每个平台（不如说是每个桌面环境）单独开发。
至于单独的页面，实际上 NextTrace 并没有提供这样的查询接口，如果要增加这个功能则必须重新实现 NextTrace 查询使用的 PoW 客户端，比较麻烦，所以暂时没有计划添加这个功能。
