### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by Whitegull** [Archeb/opentrace#31]
2023/11/20 17:24:01 dial: websocket: bad handshake
2023/11/20 17:24:02 dial: websocket: bad handshake
2023/11/20 17:24:03 dial: websocket: bad handshake
2023/11/20 17:24:04 dial: websocket: bad handshake
2023/11/20 17:24:04 dial: websocket: bad handshake
2023/11/20 17:24:07 dial: websocket: bad handshake
2023/11/20 17:24:07 dial: websocket: bad handshake
2023/11/20 17:24:08 dial: websocket: bad handshake
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x94036e]

goroutine 1 [running]:
github.com/gorilla/websocket.(*Conn).Close(0xc0000b9980?)
	github.com/gorilla/websocket@v1.5.1/conn.go:352 +0xe
github.com/nxtrace/NTrace-core/cmd.Excute.func1()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:178 +0x1b
github.com/nxtrace/NTrace-core/cmd.Excute()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:349 +0x2230
main.main()
	github.com/nxtrace/NTrace-core/main.go:8 +0xf

**Comment by Archeb** [comment]
websocket: bad handshake 一般是与 NextTrace IP 地理位置 API 连接性有关的问题，可能是网络连接异常。建议把问题向上游 https://github.com/nxtrace/NTrace-V1 报告。
