### ISSUE TITLE
异常输出

### ISSUE THREAD

**Issue by Yafeiml** [Archeb/opentrace#34]
![image](https://github.com/Archeb/opentrace/assets/16131095/0c7f15fa-54a0-4b53-93a1-e8bc868deb22)
![image](https://github.com/Archeb/opentrace/assets/16131095/d0c7f54b-22f5-40c3-afb2-5666f4cf1586)

**Comment by Archeb** [comment]
websocket: bad handshake 一般是与 NextTrace IP 地理位置 API 连接性有关的问题，可能是网络连接异常。建议把问题向上游 https://github.com/nxtrace/NTrace-V1 报告。
