### ISSUE TITLE
Windows 版本问题

### ISSUE THREAD

**Issue by lingaoyi** [Archeb/opentrace#38]
2023/11/25 11:56:14 dial: websocket: bad handshake
2023/11/25 11:56:15 dial: websocket: bad handshake
2023/11/25 11:56:16 dial: websocket: bad handshake
2023/11/25 11:56:17 dial: websocket: bad handshake
2023/11/25 11:56:18 dial: websocket: bad handshake
2023/11/25 11:56:19 dial: websocket: bad handshake
2023/11/25 11:56:20 dial: websocket: bad handshake
2023/11/25 11:56:21 dial: websocket: bad handshake
2023/11/25 11:56:22 dial: websocket: bad handshake
2023/11/25 11:56:23 dial: websocket: bad handshake
2023/11/25 11:56:25 dial: websocket: bad handshake
2023/11/25 11:56:26 dial: websocket: bad handshake
2023/11/25 11:56:27 dial: websocket: bad handshake
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xf9036e]

goroutine 1 [running]:
github.com/gorilla/websocket.(*Conn).Close(0xc00027f980?)
	github.com/gorilla/websocket@v1.5.1/conn.go:352 +0xe
github.com/nxtrace/NTrace-core/cmd.Excute.func1()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:178 +0x1b
github.com/nxtrace/NTrace-core/cmd.Excute()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:349 +0x2230
main.main()
	github.com/nxtrace/NTrace-core/main.go:8 +0xf

随便ping个网站就这样。。。。。

**Comment by Archeb** [comment]
websocket: bad handshake 一般是与 NextTrace IP 地理位置 API 连接性有关的问题，可能是网络连接异常。建议把问题向上游 https://github.com/nxtrace/NTrace-V1 报告，也可以考虑改用其他数据源或者本地数据源。
