### ISSUE TITLE
www.futbin.com

### ISSUE THREAD

**Issue by okami-chen** [Archeb/opentrace#39]
2023/11/25 16:49:24 dial: websocket: bad handshake
2023/11/25 16:49:24 dial: websocket: bad handshake
2023/11/25 16:49:25 dial: websocket: bad handshake
2023/11/25 16:49:26 dial: websocket: bad handshake
2023/11/25 16:49:26 dial: websocket: bad handshake
2023/11/25 16:49:27 dial: websocket: bad handshake
2023/11/25 16:49:28 dial: websocket: bad handshake
2023/11/25 16:49:28 dial: websocket: bad handshake
2023/11/25 16:49:29 dial: websocket: bad handshake
2023/11/25 16:49:30 dial: websocket: bad handshake
2023/11/25 16:49:31 dial: websocket: bad handshake
2023/11/25 16:49:31 dial: websocket: bad handshake
2023/11/25 16:49:32 dial: websocket: bad handshake
2023/11/25 16:49:33 dial: websocket: bad handshake
2023/11/25 16:49:33 dial: websocket: bad handshake
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x9c036e]

goroutine 1 [running]:
github.com/gorilla/websocket.(*Conn).Close(0xc000671980?)
	github.com/gorilla/websocket@v1.5.1/conn.go:352 +0xe
github.com/nxtrace/NTrace-core/cmd.Excute.func1()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:178 +0x1b
github.com/nxtrace/NTrace-core/cmd.Excute()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:349 +0x2230
main.main()
	github.com/nxtrace/NTrace-core/main.go:8 +0xf

**Comment by Archeb** [comment]
websocket: bad handshake 一般是与 NextTrace IP 地理位置 API 连接性有关的问题，可能是网络连接异常。建议把问题向上游 https://github.com/nxtrace/NTrace-V1 报告，也可以考虑改用其他数据源或者本地数据源。
