### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by simplove** [Archeb/opentrace#4]
2023/06/04 10:47:24 dial: websocket: bad handshake
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xb6fbd4]

goroutine 6 [running]:
github.com/gorilla/websocket.(*Conn).Close(0xc00010df30?)
	github.com/gorilla/websocket@v1.5.0/conn.go:345 +0x14
github.com/xgadget-lab/nexttrace/cmd.Excute.func1.1()
	github.com/xgadget-lab/nexttrace/cmd/cmd.go:161 +0x25
github.com/xgadget-lab/nexttrace/cmd.Excute.func1()
	github.com/xgadget-lab/nexttrace/cmd/cmd.go:165 +0x1a7
created by github.com/xgadget-lab/nexttrace/cmd.Excute
	github.com/xgadget-lab/nexttrace/cmd/cmd.go:150 +0x135f

**Comment by LaMP57** [comment]
M2 Mac 同样的问题

**Comment by Archeb** [comment]
一般出现 `dial: websocket: bad handshake ` 的问题，是 NextTrace 在访问 GeoIP API 的时候遇到异常，但是因为它并没有在输出中给出具体的原因，所以OpenTrace作为GUI Wrapper也没办法进一步对用户作出提示，只能原样把输出打印出来。

目前上游 NextTrace 已经在重构，只能希望他们能减少此类问题并且添加更清晰的错误输出。

**Comment by tsosunchia** [comment]
LEOMOEAPI在大陆部分地区访问受阻，这是已知的问题，除了建议您配置透明代理 or 自行配置反代没有别的办法了。

> 2023/06/04 10:47:24 dial: websocket: bad handshake panic: runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005 code=0x0 addr=0x0 pc=0xb6fbd4]
> 
> goroutine 6 [running]: github.com/gorilla/websocket.(*Conn).Close(0xc00010df30?) github.com/gorilla/websocket@v1.5.0/conn.go:345 +0x14 github.com/xgadget-lab/nexttrace/cmd.Excute.func1.1() github.com/xgadget-lab/nexttrace/cmd/cmd.go:161 +0x25 github.com/xgadget-lab/nexttrace/cmd.Excute.func1() github.com/xgadget-lab/nexttrace/cmd/cmd.go:165 +0x1a7 created by github.com/xgadget-lab/nexttrace/cmd.Excute github.com/xgadget-lab/nexttrace/cmd/cmd.go:150 +0x135f

**Comment by tsosunchia** [comment]
您可以查看[此处](https://github.com/sjlleo/nexttrace-core/issues/131#issuecomment-1579145769)，可能有助于解答您的问题
