### ISSUE TITLE
ERROR IN leomoeapi

### ISSUE THREAD

**Issue by 229033891** [Archeb/opentrace#41]
![image](https://github.com/Archeb/opentrace/assets/107928071/c4f22d60-61d8-4d4b-8a9e-d0efa5d7cb35)
![image](https://github.com/Archeb/opentrace/assets/107928071/d603dcb7-afe8-49db-8804-756b4e69a4c2)

2023/11/27 10:49:16 dial: websocket: bad handshake
2023/11/27 10:49:17 dial: websocket: bad handshake
2023/11/27 10:49:18 dial: websocket: bad handshake
2023/11/27 10:49:19 dial: websocket: bad handshake
2023/11/27 10:49:20 dial: websocket: bad handshake
2023/11/27 10:49:20 dial: websocket: bad handshake
2023/11/27 10:49:22 dial: websocket: bad handshake
2023/11/27 10:49:23 dial: websocket: bad handshake
2023/11/27 10:49:25 dial: websocket: bad handshake
2023/11/27 10:49:26 dial: websocket: bad handshake
2023/11/27 10:49:28 dial: websocket: bad handshake
2023/11/27 10:49:29 dial: websocket: bad handshake
2023/11/27 10:49:31 dial: websocket: bad handshake
2023/11/27 10:49:32 dial: websocket: bad handshake
2023/11/27 10:49:34 dial: websocket: bad handshake
2023/11/27 10:49:35 dial: websocket: bad handshake
2023/11/27 10:49:37 dial: websocket: bad handshake
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x55036e]

goroutine 1 [running]:
github.com/gorilla/websocket.(*Conn).Close(0xc0006af980?)
	github.com/gorilla/websocket@v1.5.1/conn.go:352 +0xe
github.com/nxtrace/NTrace-core/cmd.Excute.func1()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:178 +0x1b
github.com/nxtrace/NTrace-core/cmd.Excute()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:349 +0x2230
main.main()
	github.com/nxtrace/NTrace-core/main.go:8 +0xf
2023/11/27 10:49:53 dial: websocket: bad handshake
2023/11/27 10:49:53 dial: websocket: bad handshake
2023/11/27 10:49:54 dial: websocket: bad handshake
2023/11/27 10:49:54 dial: websocket: bad handshake
2023/11/27 10:49:55 dial: websocket: bad handshake
2023/11/27 10:49:55 dial: websocket: bad handshake
2023/11/27 10:49:56 dial: websocket: bad handshake
2023/11/27 10:49:57 dial: websocket: bad handshake
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x55036e]

goroutine 1 [running]:
github.com/gorilla/websocket.(*Conn).Close(0xc0000b9980?)
	github.com/gorilla/websocket@v1.5.1/conn.go:352 +0xe
github.com/nxtrace/NTrace-core/cmd.Excute.func1()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:178 +0x1b
github.com/nxtrace/NTrace-core/cmd.Excute()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:349 +0x2230
main.main()
	github.com/nxtrace/NTrace-core/main.go:8 +0xf
2023/11/27 10:55:00 dial: websocket: bad handshake
2023/11/27 10:55:01 dial: websocket: bad handshake
2023/11/27 10:55:01 dial: websocket: bad handshake
2023/11/27 10:55:02 dial: websocket: bad handshake
2023/11/27 10:55:03 dial: websocket: bad handshake
2023/11/27 10:55:03 dial: websocket: bad handshake
2023/11/27 10:55:04 dial: websocket: bad handshake
2023/11/27 10:55:05 dial: websocket: bad handshake
2023/11/27 10:55:06 dial: websocket: bad handshake
2023/11/27 10:55:06 dial: websocket: bad handshake
2023/11/27 10:55:07 dial: websocket: bad handshake
2023/11/27 10:55:08 dial: websocket: bad handshake
2023/11/27 10:55:09 dial: websocket: bad handshake
2023/11/27 10:55:09 dial: websocket: bad handshake
2023/11/27 10:55:10 dial: websocket: bad handshake
2023/11/27 10:55:11 dial: websocket: bad handshake
2023/11/27 10:55:11 dial: websocket: bad handshake
2023/11/27 10:55:12 dial: websocket: bad handshake
2023/11/27 10:55:13 dial: websocket: bad handshake
2023/11/27 10:55:13 dial: websocket: bad handshake
2023/11/27 10:55:14 dial: websocket: bad handshake
2023/11/27 10:55:15 dial: websocket: bad handshake
2023/11/27 10:55:16 dial: websocket: bad handshake
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x55036e]

goroutine 1 [running]:
github.com/gorilla/websocket.(*Conn).Close(0xc00071f980?)
	github.com/gorilla/websocket@v1.5.1/conn.go:352 +0xe
github.com/nxtrace/NTrace-core/cmd.Excute.func1()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:178 +0x1b
github.com/nxtrace/NTrace-core/cmd.Excute()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:349 +0x2230
main.main()
	github.com/nxtrace/NTrace-core/main.go:8 +0xf

**Comment by Archeb** [comment]
websocket: bad handshake 一般是与 NextTrace IP 地理位置 API 连接性有关的问题，可能是网络连接异常。建议把问题向上游 https://github.com/nxtrace/NTrace-V1 报告，也可以考虑改用其他数据源或者本地数据源。
