### ISSUE TITLE
bad handshake

### ISSUE THREAD

**Issue by xtonly** [Archeb/opentrace#45]
2023/12/07 08:42:41 dial: websocket: bad handshake
2023/12/07 08:42:46 dial: websocket: bad handshake
2023/12/07 08:42:47 dial: websocket: bad handshake
2023/12/07 08:42:51 dial: websocket: bad handshake
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4c052e]

goroutine 1 [running]:
github.com/gorilla/websocket.(*Conn).Close(0xc00007d978?)
	github.com/gorilla/websocket@v1.5.1/conn.go:352 +0xe
github.com/nxtrace/NTrace-core/cmd.Excute.func1()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:186 +0x1b
github.com/nxtrace/NTrace-core/cmd.Excute()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:357 +0x22b0
main.main()
	github.com/nxtrace/NTrace-core/main.go:8 +0xf

**Comment by Archeb** [comment]
如果您遇到了 websocket: bad handshake：

此问题是 [NextTrace](https://github.com/nxtrace/NTrace-core) 相关问题，
表示 NextTrace IP 地理位置 API 无法连接，可能是网络异常。

因为 NextTrace 默认使用的 LeoMoeAPI 是社区的免费项目，使用 CloudFlare 免费 CDN，连接性可能受地区运营商的影响。

请首先尝试更新 OpenTrace 到 1.4.1.1 版本及以上，该版本同步了最新的 NextTrace，也许可以缓解 API 的连接性问题。

如果还是不能解决，请把问题向上游 [NextTrace](https://github.com/nxtrace/NTrace-core/issues) 报告，也可以考虑在主界面右上角切换其他数据源或者在设置中配置本地数据源。
