### ISSUE TITLE
Abnormal Exit On GeoIP API Rate Exceeded

### ISSUE THREAD

**Issue by hanyan-rst** [Archeb/opentrace#5]
When using IP.SB as GeoIP API provider, may cause abnormal exit if API returns cloudflare error page 1015(You are being rate limited).
![image](https://github.com/Archeb/opentrace/assets/48790213/a0885fe7-7f92-418f-99b8-71e361fce592)

**Comment by Archeb** [comment]
This is an upstream issue too. As a GUI wrapper, all OpenTrace can do is to show a friendly message telling user that the program has exited abnormally.

**Comment by tsosunchia** [comment]
IP.SB的限制比较严格，作为NETXTTRACE开发者建议您选择其他API。
