### ISSUE TITLE
[Feature Request] 自动处理带端口的IP地址

### ISSUE THREAD

**Issue by zdm9981** [Archeb/opentrace#51]
如1.2.3.4:1234、[2001:db8::2]:1234 地址可以直接去除端口和括号

**Comment by tsosunchia** [comment]
建议一步到位  
提取`https://github.com/Archeb/opentrace/issues/51` -> `github.com`

**Comment by Archeb** [comment]
这是一个很好的提议，我计划实现它。

**Comment by Archeb** [comment]
> 建议一步到位 提取`https://github.com/Archeb/opentrace/issues/51` -> `github.com`

URL解析这个功能反而是一直都有。然后我刚才测试了一下，`IPAddress.TryParse` 这个方法可以解析 [2001:db8::2]:1234 但是不能解析 `1.2.3.4:1234`，有点奇妙。

**Comment by Archeb** [comment]
d54be1a35d39e832c1689330e1148262b9fc503e 已实现
