### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by x7c7v7i87** [Archeb/opentrace#54]
![image](https://github.com/Archeb/opentrace/assets/102465614/6e559f36-e267-4592-bdfb-3a8c5dd1c0c3)

**Comment by Archeb** [comment]
这个是NextTrace API请求失败，一般和网络环境有关。可以下一个NextTrace在终端里面跑一下看看有没有问题，如果还是有问题则可以向NextTrace那边反馈 https://github.com/nxtrace/NTrace-core/issues
