### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by okfate** [Archeb/opentrace#56]
**Describe the bug 描述你遇到的BUG**
（如果您遇到了 websocket: bad handshake，请参考 #44）
{"error":"Challenge does not exist or has expired"}

RetToken failed 3 times, please try again after a while, exit

**To Reproduce 复现方法**

**Screenshots (If applicable) 截图（如果有）**

![6d6271e6-b1df-49fd-ac55-d2f02f7df2ac](https://github.com/Archeb/opentrace/assets/36602477/f1335a4c-7e9a-4070-b954-fae596c60b8d)

**Environment 使用环境**
 - OS 操作系统：
 - Version 程序版本：

**Additional context 补充说明**

**Comment by fakeboboliu** [comment]
通常此问题是因为 PoW 服务器连接存在问题。

您可以尝试更改设置中的：
API - LeoMoeAPI PoW 服务器 项目。
