### ISSUE TITLE
清空历史记录

### ISSUE THREAD

**Issue by daoistyoudao** [Archeb/opentrace#57]
我看产品最初是不记录查询过的ip，后来有人提了重启后记录没了，所以专门为此设计了。
但是现在有一个问题，当我查询过的记录太多了时就看着很混乱，就想清空历史记录或者能单独删除是最好。
另外想了解一下windows下查询记录是在哪里保存的，因为当我把整个软件文件夹都删除重新下载新的后，查询记录依然存在。
最简单的解决方法我觉得就是告诉我记录文件在哪里存的，我自己去删掉就好了。

**Comment by Archeb** [comment]
设置和历史记录是用了一个第三方库来存储的，Windows 下的具体位置是
`C:\Users\<User Name>\AppData\Local\IsolatedStorage`
里面应该会有许多个文件夹（如果你有多个版本的话），可以全部删掉
