### ISSUE TITLE
[BUG] 异常输出

### ISSUE THREAD

**Issue by microappid** [Archeb/opentrace#65]
**Describe the bug 描述你遇到的BUG**
（如果您遇到了 websocket: bad handshake，请参考 #44）
异常输出

**To Reproduce 复现方法**

**Screenshots (If applicable) 截图（如果有）**
有
![opentrace](https://github.com/Archeb/opentrace/assets/37204902/4c201f93-1d49-48e4-8847-c99449324ecf)
![opentrace1](https://github.com/Archeb/opentrace/assets/37204902/7210d7bd-4013-4994-9105-34088656c7f2)

**Environment 使用环境**
 - OS 操作系统：Windows 10
 - Version 程序版本：最新版

**Additional context 补充说明**

**Comment by Archeb** [comment]
上游 api 不稳定，非 opentrace 问题

**Comment by microappid** [comment]
刚试了ipinfo可以使用，能设置为启动默认吗？
