### ISSUE TITLE
[BUG] nyalab powserver服务down了

### ISSUE THREAD

**Issue by tsosunchia** [Archeb/opentrace#66]
<img width="501" alt="image" src="https://github.com/Archeb/opentrace/assets/59512455/3c11418d-e885-4825-9a75-763017b1c233">
由于在一些情况下，OT默认使用nyalab作为pow服务器，因为目前服务挂了，不少用户来反馈API错误  
现在最好是修复一下这个服务或者修改默认行为

**Comment by tsosunchia** [comment]
要不直接来找我tg吧，，，
username是@p06y7

**Comment by tsosunchia** [comment]
有些用户反馈错误截图类似这个的情况，大概就是因为这个
<img width="576" alt="image" src="https://github.com/Archeb/opentrace/assets/59512455/8846e4f2-1e12-47db-88f1-c478387bfa87">

**Comment by Archeb** [comment]
我这就发个新版看看

**Comment by Archeb** [comment]
我记得默认情况下一直是 api.leo.moe 的，补回默认用 nyalabs 服务

**Comment by tsosunchia** [comment]
我不太清楚原因，有些用户来找我反馈问题  
我让他给我截图pow选择，就是默认选nyalabs了

**Comment by tsosunchia** [comment]
另外 nyalabs 还修吗（）

**Comment by Archeb** [comment]
不修了（）我去把代码改改，顺便发个新版

**Comment by tsosunchia** [comment]
> 不修了（）我去把代码改改，顺便发个新版

okk

**Comment by Archeb** [comment]
sakura又修好了。下个版本加回来（
