### ISSUE TITLE
异常输出

### ISSUE THREAD

**Issue by henryimpp** [Archeb/opentrace#67]
unexpected status code: 500
RetToken failed 3 times, please try again after a while, exit

**Comment by tsosunchia** [comment]
你用的是最新版吗

**Comment by Archeb** [comment]
请打开设置，找到API - LeoMoeAPI PoW服务器并且将它改为 api.leo.moe （默认）

**Comment by Archeb** [comment]
已修复，感谢提醒。

**Comment by henryimpp** [comment]
好的
