### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by xtonly** [Archeb/opentrace#68]
**Describe the bug 描述你遇到的BUG**
（如果您遇到了 websocket: bad handshake，请参考 #44）

2024/06/09 17:17:50 dial: websocket: bad handshake
2024/06/09 17:17:50 dial: websocket: bad handshake
2024/06/09 17:17:51 dial: websocket: bad handshake
2024/06/09 17:17:52 dial: websocket: bad handshake
2024/06/09 17:17:52 dial: websocket: bad handshake
2024/06/09 17:17:53 dial: websocket: bad handshake
2024/06/09 17:17:54 dial: websocket: bad handshake
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4a66ee]

goroutine 1 [running]:
github.com/gorilla/websocket.(*Conn).Close(0xc000115980?)
	github.com/gorilla/websocket@v1.5.1/conn.go:352 +0xe
github.com/nxtrace/NTrace-core/cmd.Excute.func1()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:188 +0x1b
github.com/nxtrace/NTrace-core/cmd.Excute()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:359 +0x22fb
main.main()
	github.com/nxtrace/NTrace-core/main.go:8 +0xf

**To Reproduce 复现方法**

**Screenshots (If applicable) 截图（如果有）**

**Environment 使用环境**
 - OS 操作系统：WIN 11
 - 
 - Version 程序版本：
[Version 1.4.3.0](https://github.com/Archeb/opentrace/releases/tag/v1.4.3.0)

**Additional context 补充说明**

**Comment by Archeb** [comment]
NextTrace API 网络问题，不属于本项目
