### ISSUE TITLE
Duplicate GeoIP Info in English Lang

### ISSUE THREAD

**Issue by hanyan-rst** [Archeb/opentrace#7]
![image](https://github.com/Archeb/opentrace/assets/48790213/d94d58a4-dd1e-47b5-b9f2-c386cb476d4e)
![image](https://github.com/Archeb/opentrace/assets/48790213/abad5799-2bb0-43ea-815f-cbfbaf31ffd3)

**Comment by Archeb** [comment]
This is more or less an upstream problem, mainly how they store and display geoip information. I would suggest you report this to NextTrace and LeoMoeAPI.
