### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by oozj** [Archeb/opentrace#70]
**Describe the bug 描述你遇到的BUG**
（如果您遇到了 websocket: bad handshake，请[参考这里](https://www.github.com/Archeb/opentrace/issues/44)）
2024/06/17 17:07:49 dial: websocket: bad handshake
2024/06/17 17:07:49 dial: websocket: bad handshake
2024/06/17 17:07:50 dial: websocket: bad handshake
2024/06/17 17:07:51 dial: websocket: bad handshake
2024/06/17 17:07:52 dial: websocket: bad handshake
2024/06/17 17:07:52 dial: websocket: bad handshake
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xdd66ee]

goroutine 1 [running]:
github.com/gorilla/websocket.(*Conn).Close(0xc00011d980?)
	github.com/gorilla/websocket@v1.5.1/conn.go:352 +0xe
github.com/nxtrace/NTrace-core/cmd.Excute.func1()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:188 +0x1b
github.com/nxtrace/NTrace-core/cmd.Excute()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:359 +0x22fb
main.main()
	github.com/nxtrace/NTrace-core/main.go:8 +0xf

**To Reproduce 复现方法**

**Screenshots (If applicable) 截图（如果有）**

**Environment 使用环境**
 - OS 操作系统：
 - Version 程序版本：

**Additional context 补充说明**

**Comment by tsosunchia** [comment]
> （如果您遇到了 websocket: bad handshake，请[参考这里](https://www.github.com/Archeb/opentrace/issues/44)）

ISSUE模板里有提到该问题
