### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by haiking419** [Archeb/opentrace#72]
**Describe the bug 描述你遇到的BUG**
（如果您遇到了 websocket: bad handshake，请[参考这里](https://www.github.com/Archeb/opentrace/issues/44)）

**To Reproduce 复现方法**

**Screenshots (If applicable) 截图（如果有）**
![image](https://github.com/user-attachments/assets/17765954-afc3-45d9-a101-c94b1ed29bff)

**Environment 使用环境**
 - OS 操作系统：
 - Version 程序版本：

**Additional context 补充说明**

**Comment by fakeboboliu** [comment]
https://github.com/microsoft/terminal/issues/6391

看起来是有什么东西搞烂了你的系统，建议自行检查，不行就使用万能的重装 XD

**Comment by haiking419** [comment]
您好！      已收到您的邮件，我将尽快给您回复。——如有急事，请直接电话联系。（来自QQ邮箱的自动回复邮件）
