### ISSUE TITLE
[Feature Request] Windows软件安装说明疑问

### ISSUE THREAD

**Issue by Hinlavic** [Archeb/opentrace#73]
**Is your feature request related to a problem? Please describe. 您所请求的功能是否和某个问题有关？如果有，请说明**

**Describe the solution you'd like 描述您想要的功能**

- 从Release下载的win-x64.zip中的“nexttrace.exe”是不是就是“使用方法”中提到的必须的“NextTrace V1”核心？因为在使用过程中遇到了一些错误，不确定是不是因为缺少这个核心文件导致的。
- 从“NextTrace V1”项目Release下载的“nexttrace_windows_amd64.exe”，不修改文件名，直接放到opentrace的目录能被正确识别，并优先于“nexttrace.exe”被使用吗？因为opentrace路由路径地图可视化显示的时候，似乎经常缺少地理位置的第一跳或者最后一跳，尽管地理位置是明确的城市，不清楚是不是核心的问题，所有有此一问。

**Describe alternatives you've considered (If applicable) 可能备选方案（如果有）**

**Additional context 补充说明**

**Comment by Archeb** [comment]
- nexttrace.exe就是核心，两个文件名都可以被识别并使用
- 遇到缺少地理位置的情况请提供直接运行 nexttrace 命令的结果、opentrace 截图。有时候部分城市在标注的时候没有正确与经纬度匹配导致文字显示正常但无地理位置，这种情况请到nexttrace那边反馈一下。
