### ISSUE TITLE
[BUG] 第一次打开就崩溃了

### ISSUE THREAD

**Issue by Sevenzhi** [Archeb/opentrace#76]
2024/09/13 11:47:26 dial: websocket: bad handshake
2024/09/13 11:47:27 dial: websocket: bad handshake
2024/09/13 11:47:28 dial: websocket: bad handshake
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xa566ee]

goroutine 1 [running]:
github.com/gorilla/websocket.(*Conn).Close(0xc0000af980?)
	github.com/gorilla/websocket@v1.5.1/conn.go:352 +0xe
github.com/nxtrace/NTrace-core/cmd.Excute.func1()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:188 +0x1b
github.com/nxtrace/NTrace-core/cmd.Excute()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:359 +0x22fb
main.main()
	github.com/nxtrace/NTrace-core/main.go:8 +0xf
2024/09/13 11:47:58 dial: websocket: bad handshake
2024/09/13 11:47:58 dial: websocket: bad handshake
2024/09/13 11:47:59 dial: websocket: bad handshake
2024/09/13 11:48:00 dial: websocket: bad handshake
2024/09/13 11:48:02 dial: websocket: bad handshake
2024/09/13 11:48:03 dial: websocket: bad handshake
2024/09/13 11:48:05 dial: websocket: bad handshake
2024/09/13 11:48:06 dial: websocket: bad handshake
2024/09/13 11:48:07 dial: websocket: bad handshake
2024/09/13 11:48:08 dial: websocket: bad handshake
2024/09/13 11:48:09 dial: websocket: bad handshake
2024/09/13 11:48:10 dial: websocket: bad handshake
2024/09/13 11:48:12 dial: websocket: bad handshake
2024/09/13 11:48:13 dial: websocket: bad handshake
2024/09/13 11:48:14 dial: websocket: bad handshake
2024/09/13 11:48:15 dial: websocket: bad handshake
2024/09/13 11:48:16 dial: websocket: bad handshake
2024/09/13 11:48:17 dial: websocket: bad handshake
2024/09/13 11:48:19 dial: websocket: bad handshake
2024/09/13 11:48:20 dial: websocket: bad handshake
2024/09/13 11:48:21 dial: websocket: bad handshake
2024/09/13 11:48:23 dial: websocket: bad handshake
2024/09/13 11:48:24 dial: websocket: bad handshake
2024/09/13 11:48:25 dial: websocket: bad handshake
2024/09/13 11:48:27 dial: websocket: bad handshake
2024/09/13 11:48:28 dial: websocket: bad handshake
2024/09/13 11:48:29 dial: websocket: bad handshake
2024/09/13 11:48:30 dial: websocket: bad handshake
2024/09/13 11:48:31 dial: websocket: bad handshake
2024/09/13 11:52:48 dial: websocket: bad handshake
2024/09/13 11:52:50 dial: websocket: bad handshake
2024/09/13 11:52:50 dial: websocket: bad handshake
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xa566ee]

goroutine 1 [running]:
github.com/gorilla/websocket.(*Conn).Close(0xc000139980?)
	github.com/gorilla/websocket@v1.5.1/conn.go:352 +0xe
github.com/nxtrace/NTrace-core/cmd.Excute.func1()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:188 +0x1b
github.com/nxtrace/NTrace-core/cmd.Excute()
	github.com/nxtrace/NTrace-core/cmd/cmd.go:359 +0x22fb
main.main()
	github.com/nxtrace/NTrace-core/main.go:8 +0xf（如果您遇到了 websocket: bad handshake，请[参考这里](https://www.github.com/Archeb/opentrace/issues/44)）

**To Reproduce 复现方法**

**Screenshots (If applicable) 截图（如果有）**

**Environment 使用环境**
 - OS 操作系统：win11
 - Version 程序版本：最新版

**Additional context 补充说明**

**Comment by fakeboboliu** [comment]
![image](https://github.com/user-attachments/assets/be763ac0-db9c-47b1-bff8-947576182580)
