### ISSUE TITLE
[Feature Request] 希望新增最大跃点数设置  hoping for maximum_hops settings

### ISSUE THREAD

**Issue by youhunluanma** [Archeb/opentrace#78]
**Is your feature request related to a problem? Please describe. 您所请求的功能是否和某个问题有关？如果有，请说明**

**Describe the solution you'd like 描述您想要的功能**

在CMD里Tracert，有一个参数是maximum_hops，可以自定义最大跟踪跳数，不仅仅局限于默认的30跳
希望本软件也能跟进这个设置，如果有时候tra丢了，更多的跳数起码可以知道丢哪儿去了（不

Use command Tracert in cmd, you can choose an option "-h" which means change maximum_hops value instead of deafult (30).
Hoping for addding this setting into NextTrace App for more possibility :)

**Describe alternatives you've considered (If applicable) 可能备选方案（如果有）**

**Additional context 补充说明**
![image](https://github.com/user-attachments/assets/a4f9ded8-729b-45ef-be77-1bf34105bd2c)

**Comment by Archeb** [comment]
看来你已经找到了 😋

**Comment by youhunluanma** [comment]
> 看来你已经找到了 😋

我的锅，眼瞎了，换个新问题问一下作者吧（

**Comment by youhunluanma** [comment]
> 看来你已经找到了 😋

我是小丑🤡🤡🤡

其实还是有个小问题，我直接搁这儿问吧，我注意到”Windows 暂不支持 TCP/UDP Traceroute“，这是Windows的限制，还是说实现比较困难所以暂时没有做呢，比较感兴趣他们和ICMP的区别，我不是特别懂这个还请轻点儿喷（

**Comment by Archeb** [comment]
实现比较困难，不过这个主要是上游项目（NextTrace）的问题。

**Comment by tsosunchia** [comment]
> 实现比较困难，不过这个主要是上游项目（NextTrace）的问题。

也不是 NextTrace 问题，是上游依赖 net 库的问题。
