### ISSUE TITLE
[Feature Request] 新视图

### ISSUE THREAD

**Issue by tqangxl** [Archeb/opentrace#79]
**Is your feature request related to a problem? Please describe. 您所请求的功能是否和某个问题有关？如果有，请说明**

**Describe the solution you'd like 描述您想要的功能**
![image](https://github.com/user-attachments/assets/ddfbd089-b7e0-4c69-86ae-f24b4e378b1a)
![image](https://github.com/user-attachments/assets/7b0bf002-ab45-4d76-8f07-5b57560ddb78)
![image](https://github.com/user-attachments/assets/717d272e-8e58-4501-968b-9f380ffb4ff7)

**Describe alternatives you've considered (If applicable) 可能备选方案（如果有）**

**Additional context 补充说明**

**Comment by fakeboboliu** [comment]
太高级了，欢迎 PR
