### ISSUE TITLE
中文输入法冲突

### ISSUE THREAD

**Issue by People-11** [Archeb/opentrace#9]
按下回车键时，OpenTrace 会解析输入的目标，但是使用中文输入法按下回车输出英文时，也会触发解析。如果此时输入的是不正确的目标，则会报 could not find host 错误。

**Comment by Archeb** [comment]
已在 064eec17594ee87fe5eb97d42f1108d258867f77 中修复

**Comment by tsosunchia** [comment]
@Archeb macOS里也有此问题（

**Comment by Archeb** [comment]
> @Archeb macOS里也有此问题（

确实，重新开启此issue

**Comment by Archeb** [comment]
macOS 的问题在 f0ee013e15849e27ea106d07f35bb8e3644556e6 中也被一同修复。

**Comment by Archeb** [comment]
macOS 感觉上是修不好了……
因为在 .NET 上我缺乏必要的平台 API 来检测输入法状态；而 macOS 在输入法开启的状态下仍然会完整的把 KeyDown、KeyUp 等事件传给程序（Windows上只会把KeyUp传过来），所以对于程序来说似乎没有办法判别。

但是根据我的测试，以在macOS上追踪 baidu.com 为例：
当用户打出 baidu.com 中的英文句点时，前面的内容将按照原文（baidu）被输入进文本框。只要用户输入完 com 才按enter，就能正确完整输入域名并且开始追踪。

该问题暂时被列为 wontfix
